service: lambda-wake-up

provider:
  name: aws
  runtime: nodejs6.10
  cfLogs: true
  stage: production
  region: ap-northeast-1

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true # enable auto including node_modules
  graphiql:
    babelOptions:
      presets: [es2015, es2016, stage-0]
      plugins: [transform-runtime]

functions:
  wakeup:
    handler: handler.wakeup
    events:
      - schedule: rate(20 minutes)
